### ISSUE TITLE
Resource handler script can not be found using last version of this server

### ISSUE THREAD

**Issue by VaSimple** [Tadas/PServeREST#3]
GET request from "http://localhost:1234/Name" or "http://localhost:1234/Time" will return the message "Resource handler script not found".
The reason why this is happening is because root path of the script is at \PServeREST\Public, not at \PServeREST, so the script it trying to reach '\PServeREST\Public\Resources' path, not '\PServeREST\Resources'.

Replacing 22nd line of Invoke-PServeREST.ps1 with `$ResourceHandlerFile = Join-Path $PSScriptRoot "..\Resources\$Resource.ps1"` should fix this issue.
[Invoke-PServeREST.zip](https://github.com/Tadas/PServeREST/files/3271454/Invoke-PServeREST.zip)

**Comment by Tadas** [comment]
Thanks!
